APP/TIP_Project/urls.py
from django.contrib import admin
from django.urls import path, include

from app01 import views
from suburb_finder.views import DashbordView
from dataviz import views as dataviz_views
from suburb_finder import views as suburb_finder_views

from search.views import SearchFilterView, models_api, export_csv, MapView, DashbordView

urlpatterns = [

    path("suburb_finder/", suburb_finder_views.index, name = 'suburb_finder'),
    path("", suburb_finder_views.index, name = 'suburb_finder'),

    path("admin/", admin.site.urls),
    
    path("address/list/", views.address_list, name="data_management"),
    path("address/add/", views.address_add),
    path("address/<int:nid>/edit/", views.address_edit),
    path("address/multi/", views.address_multi),
    path("address/delete/", views.address_delete),
    #

    path("piano/list/", views.piano_list),
    path("piano/add/", views.piano_add),
    path("piano/<int:nid>/edit/", views.piano_edit),
    path("piano/multi/", views.piano_multi),
    path("piano/delete/", views.piano_delete),

    path("user/list/", views.user_list),
    path("user/add/", views.user_add),
    path("user/<int:nid>/edit/", views.user_edit),
    path("user/multi/", views.user_multi),
    path("user/delete/", views.user_delete),

    path("cpa/list/", views.cpa_list),
    path("cpa/add/", views.cpa_add),
    path("cpa/<int:nid>/edit/", views.cpa_edit),
    path("cpa/multi/", views.cpa_multi),
    path("cpa/delete/", views.cpa_delete),

    path("tuning/list/", views.tuning_list),
    path("tuning/add/", views.tuning_add),
    path("tuning/<int:nid>/edit/", views.tuning_edit),
    path("tuning/multi/", views.tuning_multi),
    path("tuning/delete/", views.tuning_delete),

    path("map/test/", views.map_test),
    path("map/download/", views.map_download),

    path("tuning/check/", views.tuning_check),
    path("tuning/<int:nid>/book/", views.tuning_book),
    path("cpa/new/", views.cpa_new),


    path("select/user/", views.select_user),
    path("select/<int:nid>/address/", views.select_address),
    path("select/<int:uid>/<int:aid>/piano/", views.select_piano),
    path("select/<int:uid>/<int:aid>/<int:pid>/cpa/", views.select_cpa),
    path("select/<int:cid>/check/", views.select_check),

    path("dataviz/", dataviz_views.index,name="map"),

    # data visualisation - yongbin test
    path("chart/list/", views.chart_list),
    path("chart/bar/", views.chart_bar),

    # path('admin/', admin.site.urls),
    # path('', DashbordView, name='dashboard'),
    path('search/', SearchFilterView, name='search'),
    path('dashboard/', DashbordView, name='dashboard'),
    # path('map/',MapView, name='map'),
    path('api/models/', models_api, name='models_api'),
    path('export-csv/', export_csv, name='export_csv'),

]

APP/app01/models.py
from django.db import models
from django.core.validators import RegexValidator


# Create your models here.

class User(models.Model):
    uid = models.BigAutoField(verbose_name="User ID", primary_key=True)
    first_name = models.CharField(verbose_name="First Name", max_length=128)
    last_name = models.CharField(verbose_name="Last Name", max_length=128)
    email = models.EmailField(verbose_name="email", max_length=128, null=True, blank=True)

    gender_choices = (
        ("Male", "Male"),
        ("Female", "Female"),
    )
    gender = models.CharField(verbose_name="Gender", choices=gender_choices, null=True, blank=True, default="Upright",
                              max_length=8)
    phone_regex = RegexValidator(regex=r'^0\d{9}',
                                 message="Phone number must be entered in the format: '0434401234'. Up to 10 digits allowed.")

    phone_number = models.CharField(validators=[phone_regex], verbose_name="Phone Number", max_length=32, unique=True)

    def __str__(self):
        return "UID:" + str(self.uid) + ", " + self.first_name + " " + self.last_name + ", " + self.phone_number


class Address(models.Model):
    aid = models.BigAutoField(verbose_name="Address ID", primary_key=True)
    address = models.CharField(verbose_name="Address", max_length=256)
    suburb = models.CharField(verbose_name="Suburb", max_length=64)
    postcode = models.CharField(verbose_name="Postcode", max_length=8)
    lat = models.DecimalField(verbose_name="Latitude", max_digits=15, decimal_places=12)
    long = models.DecimalField(verbose_name="Longitude", max_digits=15, decimal_places=12)

    def __str__(self):
        return "AID:" + str(self.aid) + ", " + self.address + ", " + self.suburb + ", " + self.postcode


class Piano(models.Model):
    pid = models.BigAutoField(verbose_name="Piano ID", primary_key=True)
    brand = models.CharField(verbose_name="Brand", max_length=256)
    model = models.CharField(verbose_name="Model", max_length=64)
    sub_model = models.CharField(verbose_name="Sub Model", max_length=64, null=True, blank=True)
    colour = models.CharField(verbose_name="colour", max_length=64, null=True, blank=True)

    # type_choices = (
    #     (0, "Upright"),
    #     (1, "Grand"),
    # )
    # type = models.SmallIntegerField(verbose_name="Piano Type", choices=type_choices, null=True, blank=True)
    type_choices = (
        ("Upright", "Upright"),
        ("Grand", "Grand"),
    )
    type = models.CharField(verbose_name="Piano Type", choices=type_choices, null=True, blank=True, default="Upright",
                            max_length=8)

    def __str__(self):
        return "PID:" + str(self.pid) + ", " + self.brand + ", " + self.model


class CPA(models.Model):
    cid = models.BigAutoField(verbose_name="CID", primary_key=True)
    # uid = models.ForeignKey(to="User", to_field="uid", verbose_name="User ID")
    uid = models.ForeignKey(to="User", to_field="uid", null=True, blank=True, on_delete=models.SET_NULL,
                            verbose_name="User ID")
    # when del id data in Address,Piano, set the value to null
    aid = models.ForeignKey(to="Address", to_field="aid", null=True, blank=True, on_delete=models.SET_NULL,
                            verbose_name="AID")
    pid = models.ForeignKey(to="Piano", to_field="pid", null=True, blank=True, on_delete=models.SET_NULL,
                            verbose_name="PID")
    sn = models.CharField(verbose_name="SN Number", max_length=256, null=True, blank=True)
    sales = models.CharField(verbose_name="Sales ID", max_length=8, null=True, blank=True)
    co_sales = models.CharField(verbose_name="Co_Sales ID", max_length=8, null=True, blank=True)
    sold_date = models.DateField(verbose_name="Sold Date", null=True, blank=True)

    choices = (
        ("Yes", "Yes"),
        ("No", "No"),
    )
    active = models.CharField(verbose_name="Active", choices=choices, default="Yes", max_length=8)
    directly_sold = models.CharField(verbose_name="Directly Sold", choices=choices, default="Yes", max_length=8)

    def __str__(self):
        return '%s %s %s, SN:%s, Sold Date:%s' % (self.uid, self.aid, self.pid, self.sn, self.sold_date)


class Tuning(models.Model):
    tid = models.BigAutoField(verbose_name="Tuning ID", primary_key=True)
    mid = models.CharField(verbose_name="Machinist ID", max_length=8)
    # when del cid data in CPA, set the value to null
    cid = models.ForeignKey(to="CPA", to_field="cid", null=True, blank=True, on_delete=models.SET_NULL)
    tuning_date = models.DateField(verbose_name="Tuning Date", null=True, blank=True)
    piano_condition = models.CharField(verbose_name="Piano Condition", max_length=256, null=True, blank=True)

APP/app01/views.py
import random
import googlemaps
import csv
import pandas as pd
from geopy import distance
import geopandas as gpd
import os
import numpy as np
import os
import boto3
from botocore.exceptions import ClientError
from openpyxl import load_workbook
import xlwt

from django.conf import settings
from django.shortcuts import render, HttpResponse, redirect
from django import forms
from django.db.models import Q

from app01 import models
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.views.decorators.csrf import csrf_exempt
from app01.utilis.encrypt import md5
from app01.utilis.code import check_code
from django.utils.safestring import mark_safe
from io import BytesIO
import json
from app01.utilis.pagination import Pagination
from django.http import JsonResponse
from datetime import datetime

# Create your views here.
sheet_name = ['User', 'Address', 'Piano', 'CPA', 'Tuning']

user_fields = ['uid', 'first_name', 'last_name', 'email', 'gender', 'phone_number']
address_fields = ['aid', 'address', 'suburb', 'postcode', 'lat', 'long']
piano_fields = ['pid', 'brand', 'model', 'sub_model', 'colour', 'type']
cpa_fields = ['cid', 'uid_id', 'aid_id', 'pid_id', 'sn', 'sales', 'co_sales', 'sold_date', 'active', 'directly_sold']
tuning_fields = ['tid', 'mid', 'cid_id', 'tuning_date', 'piano_condition']

data_column = {
    'User': user_fields,
    'Address': address_fields,
    'Piano': piano_fields,
    'CPA': cpa_fields,
    'Tuning': tuning_fields,
}

access_key = settings.ACCESS_KEY
access_secret = settings.ACCESS_SECRET
bucket_name = settings.BUCKET_NAME
bucket_function_open = False


def data_excel_file():
    user_queryset = models.User.objects.all()
    address_queryset = models.Address.objects.all()
    piano_queryset = models.Piano.objects.all()
    cpa_queryset = models.CPA.objects.all()
    tuning_queryset = models.Tuning.objects.all()

    data_queryset = {
        'User': user_queryset,
        'Address': address_queryset,
        'Piano': piano_queryset,
        'CPA': cpa_queryset,
        'Tuning': tuning_queryset,
    }

    wb = xlwt.Workbook()
    for name in sheet_name:
        ws = wb.add_sheet(name)
        row_num = 0
        columns = data_column[name]
        for col_num in range(len(columns)):
            # head of the table
            ws.write(row_num, col_num, columns[col_num])
        if name == "User":
            for row in data_queryset[name]:
                row_num += 1
                ws.write(row_num, 0, row.uid)
                ws.write(row_num, 1, row.first_name)
                ws.write(row_num, 2, row.last_name)
                ws.write(row_num, 3, row.email)
                ws.write(row_num, 4, row.gender)
                ws.write(row_num, 5, row.phone_number)
        elif name == "Address":
            for row in data_queryset[name]:
                row_num += 1
                ws.write(row_num, 0, row.aid)
                ws.write(row_num, 1, row.address)
                ws.write(row_num, 2, row.suburb)
                ws.write(row_num, 3, row.postcode)
                ws.write(row_num, 4, row.lat)
                ws.write(row_num, 5, row.long)
        elif name == "Piano":
            for row in data_queryset[name]:
                row_num += 1
                ws.write(row_num, 0, row.pid)
                ws.write(row_num, 1, row.brand)
                ws.write(row_num, 2, row.model)
                ws.write(row_num, 3, row.sub_model)
                ws.write(row_num, 4, row.colour)
                ws.write(row_num, 5, row.type)
        elif name == "CPA":
            for row in data_queryset[name]:
                row_num += 1
                ws.write(row_num, 0, row.cid)
                ws.write(row_num, 1, row.uid_id)
                ws.write(row_num, 2, row.aid_id)
                ws.write(row_num, 3, row.pid_id)
                ws.write(row_num, 4, row.sn)
                ws.write(row_num, 5, row.sales)
                ws.write(row_num, 6, row.co_sales)
                ws.write(row_num, 7, str(row.sold_date))
                ws.write(row_num, 8, row.active)
                ws.write(row_num, 9, row.directly_sold)
        elif name == "Tuning":
            for row in data_queryset[name]:
                row_num += 1
                ws.write(row_num, 0, row.tid)
                ws.write(row_num, 1, row.mid)
                ws.write(row_num, 2, row.cid_id)
                ws.write(row_num, 3, str(row.tuning_date))
                ws.write(row_num, 4, row.piano_condition)
    media_root = settings.MEDIA_ROOT
    media_path = os.path.join(media_root, "test.xls")
    # print(media_path)
    wb.save(media_path)


def upload_s3():
    file_name = datetime.now().strftime("%Y%m%d%H%M%S") + str(random.randint(1000, 9999)) + ".xls"
    media_root = settings.MEDIA_ROOT
    excel_path = os.path.join(media_root, "test.xls")
    client_s3 = boto3.client(
        "s3",
        aws_access_key_id=access_key,
        aws_secret_access_key=access_secret

    )
    client_s3.upload_file(
        excel_path,
        bucket_name,
        file_name
    )


def s3_upload(function_open):
    if function_open:
        data_excel_file()
        upload_s3()
    else:
        pass


class AddressModelForm(forms.ModelForm):
    class Meta:
        model = models.Address
        fields = "__all__"
        # exclude = ("lat", "long")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}


def address_list(request):
    search_value = request.POST.get("q", "")

    if search_value:
        queryset = models.Address.objects.filter(
            Q(address__icontains=search_value) | Q(suburb__icontains=search_value) |
            Q(postcode__icontains=search_value)).order_by("-aid")
        # queryset = models.Address.objects.filter(
        #     Q(address__icontains=search_value) & Q(suburb__icontains=search_value)).order_by("-aid")
        form = AddressModelForm()
        content = {
            "form": form,
            "queryset": queryset,
            "search_value": search_value
        }
        return render(request, "address_list.html", content)

    queryset = models.Address.objects.all().order_by("-aid")
    page_object = Pagination(request, queryset)

    form = AddressModelForm()
    content = {
        "form": form,
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
        "search_value": search_value

    }
    return render(request, "address_list.html", content)


def address_add(request):
    title = "Add New Address"
    if request.method == "GET":
        form = AddressModelForm()
        return render(request, "address_add.html", {"form": form, "title": title})

    form = AddressModelForm(data=request.POST)
    if form.is_valid():
        address = request.POST.get("address")
        suburb = request.POST.get("suburb")
        postcode = request.POST.get("postcode")
        lat = request.POST.get("lat")
        long = request.POST.get("long")
        # print(address)

        exists = models.Address.objects.filter(address=address, suburb=suburb, postcode=postcode).exists()
        if exists:
            address_id = models.Address.objects.filter(address=address, suburb=suburb, postcode=postcode).first().aid
            form = AddressModelForm()
            alert = f"The address is exist, and the Address ID is {address_id}, please double check"
            return render(request, "address_add.html", {"form": form, "alert": alert})

        # print(address, suburb, postcode, lat, long)
        form.save()
        # rewrite/create the file test.xls in media folder
        # upload the test.xls file to aws s3 bucket
        s3_upload(bucket_function_open)
        return redirect("/address/list/")
    return render(request, "address_add.html", {"form": form, "title": title})


def address_multi(request):
    # "bulk upload"
    file_object = request.FILES.get("exc")
    # print(type(file_object))
    wb = load_workbook(file_object)
    sheet = wb.worksheets[1]
    # from the second rows min_row=2
    for row in sheet.iter_rows(min_row=2):
        aid = row[0].value
        address = row[1].value
        suburb = row[2].value
        postcode = row[3].value
        latitude = row[4].value
        longitude = row[5].value
        models.Address.objects.create(aid=aid, address=address, suburb=suburb, postcode=postcode,
                                      lat=latitude, long=longitude)

    # rewrite/create the file test.xls in media folder
    # upload the test.xls file to aws s3 bucket
    s3_upload(bucket_function_open)
    return redirect("/address/list/")


def address_edit(request, nid):
    row_object = models.Address.objects.filter(aid=nid).first()
    title = "Edit Address"

    if request.method == "GET":
        form = AddressModelForm(instance=row_object)
        return render(request, "address_add.html", {"form": form, "title": title})

    form = AddressModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        # rewrite/create the file test.xls in media folder
        # upload the test.xls file to aws s3 bucket
        s3_upload(bucket_function_open)
        return redirect("/address/list/")
    else:
        return render(request, "address_add.html", {"form": form, "title": title})


def address_delete(request):
    uid = request.GET.get("uid")
    exist = models.Address.objects.filter(aid=uid)

    if not exist:
        return JsonResponse({"status": False, "error": "Data not exist!"})
    models.Address.objects.filter(aid=uid).delete()
    # rewrite/create the file test.xls in media folder
    # upload the test.xls file to aws s3 bucket
    s3_upload(bucket_function_open)
    return JsonResponse({"status": True})


class UserModelForm(forms.ModelForm):
    class Meta:

APP/app01/templates/add.html
{% extends "layout.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}">

{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>

                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}

    <script src="{% static "plugins/bootstrap-datepicker/js/bootstrap-datepicker.js" %}">
    </script>
    <script>
        $(function () {
            $('#dt').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '2019-01-01',
                autoclose: true
            });

        })
    </script>
{% endblock %}

APP/app01/templates/add_cpa.html
{% extends "layout.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}">

{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>

                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}

    <script src="{% static "plugins/bootstrap-datepicker/js/bootstrap-datepicker.js" %}">
    </script>
    <script>
        $(function () {
            $('#id_sold_date').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '2019-01-01',
                autoclose: true
            });

        })
    </script>
{% endblock %}

APP/app01/templates/add_tuning.html
{% extends "layout.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}">

{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>

                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}

    <script src="{% static "plugins/bootstrap-datepicker/js/bootstrap-datepicker.js" %}">
    </script>
    <script>
        $(function () {
            $('#id_tuning_date').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '2019-01-01',
                autoclose: true
            });

        })
    </script>
{% endblock %}

APP/app01/templates/cpa_new.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
        </div>
        <form method="post" novalidate>
            {% csrf_token %}

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">User Infomation</h3>
                </div>

                <span style="color: red">{{ user_alert }}</span>
                <div class="panel-body">
                    {% csrf_token %}
                    {% for field in form.visible_fields|slice:":5" %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>

                        </div>
                    {% endfor %}

                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Address Infomation</h3>
                </div>
                <div class="panel-body">
                    {% for field in form.visible_fields|slice:"5:10" %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>

                        </div>
                    {% endfor %}

                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Piano Infomation</h3>
                </div>
                <div class="panel-body">
                    {% for field in form.visible_fields|slice:"10:15" %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>

                        </div>
                    {% endfor %}

                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">CPA Infomation</h3>
                </div>
                <div class="panel-body">
                    {% for field in form.visible_fields|slice:"15:" %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color:red;">{{ field.errors.0 }}</span>

                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Submit</button>

                </div>
            </div>
        </form>

    </div>

{% endblock %}
{% block js %}
    <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDW2OlR6mwJKIHg4xcvkV4eVFexO6UL4KM&callback=initAutocomplete&libraries=places&v=weekly"
            defer
    ></script>

    <script>
        /**
         * @license
         * Copyright 2019 Google LLC. All Rights Reserved.
         * SPDX-License-Identifier: Apache-2.0
         */
// This sample uses the Places Autocomplete widget to:
// 1. Help the user select a place
// 2. Retrieve the address components associated with that place
// 3. Populate the form fields with those address components.
// This sample requires the Places library, Maps JavaScript API.
// Include the libraries=places parameter when you first load the API.
// For example: <script
// src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
        let autocomplete;
        let address1Field;
        let address2Field;
        let postalField;

        function initAutocomplete() {
            address1Field = document.querySelector("#id_address");
            postalField = document.querySelector("#id_postcode");
            // Create the autocomplete object, restricting the search predictions to
            // addresses in mel rectangle range.
            const sw = {lat: -38.594825, lng: 144.304146};
            const ne = {lat: -37.249765, lng: 145.842310}
            const cornerBounds = new google.maps.LatLngBounds(sw, ne);
            autocomplete = new google.maps.places.Autocomplete(
                address1Field,
                {
                    fields: ["address_components", "geometry"],
                    types: ["address"],
                });
            autocomplete.setBounds(cornerBounds)
            address1Field.focus();
            // When the user selects an address from the drop-down, populate the
            // address fields in the form.
            autocomplete.addListener("place_changed", fillInAddress);
        }

        function fillInAddress() {
            // Get the place details from the autocomplete object.
            const place = autocomplete.getPlace();
            let address1 = "";
            let unit = "";
            document.getElementById('id_lat').value = place.geometry.location.lat();
            document.getElementById('id_long').value = place.geometry.location.lng();
            // Get each component of the address from the place details,
            // and then fill-in the corresponding field on the form.
            // place.address_components are google.maps.GeocoderAddressComponent objects
            // which are documented at http://goo.gle/3l5i5Mr
            for (const component of place.address_components) {
                // @ts-ignore remove once typings fixed
                const componentType = component.types[0];

                switch (componentType) {

                    case "street_number": {
                        address1 = `${component.long_name} ${address1}`;
                        break;
                    }
                    case "subpremise":
                        unit = component.long_name
                        break;

                    case "route": {
                        address1 += component.long_name;
                        break;
                    }

                    case "postal_code": {
                        document.querySelector("#id_postcode").value = component.long_name;

                        break;
                    }

                    case "locality":
                        document.querySelector("#id_suburb").value = component.long_name;
                        break;


                }
            }

            if (unit == "") {
                address1Field.value = address1;
            } else {
                address1Field.value = `${unit.toString()}/${address1}`;
            }

            // After filling the form with address components from the Autocomplete
            // prediction, set cursor focus on the second address line to encourage
            // entry of subpremise information such as apartment, unit, or floor number.
            address2Field.focus();
        }

        window.initAutocomplete = initAutocomplete;

    </script>

{% endblock %}